[project]
name = "py_maskinporten"
version = "0.9.0"
description = "Fetch Maskinporten token"
readme = "README.md"
authors = [
    { name = "Novica Nakov", email = "nnovica@gmail.com" }
]
license = "EUPL-1.2"

requires-python = ">=3.13"
dependencies = [
    "datetime",
    "jwcrypto",
    "httpx",
    "pyjwt",
    "uuid"
]

[project.scripts]
py_maskinporten = "py_maskinporten:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "asgiref>=3.8.1",
    "ruff>=0.6.1",
    "pyright>=1.1.377",
    "pytest>=8.3.3",
]
