# adopted from https://pdoc.dev/docs/pdoc.html
name: website

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - main

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: astral-sh/setup-uv@v5

      - name: Install docs deps
        run: uv sync --group docs

      - name: Generate documentation
        run: uv run pdoc ./src/pymaskinporten -o ./docs

      - name: Upload docs
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
